F/timer image
Next-Room/NextRoom-be pull request #152
Opened 2024-12-10 04:40 UTC by im-gnar

### PR 타입
- [ ] 기능 추가
- [ ] 코드 리팩토링

### 반영 브랜치
feature/{issue_title} → develop

### 작업 사항
- timer 관련 API 추가
  - 수정 기능은 삭제 후 재추가로 정의되어있어 put 은 생성하지 않았습니다
- 이후 다른 종류의 image 가 추가될 지 몰라 timer prefix 로 지정했습니다
- theme domain 의 의존도를 분리하기 위해 service 를 생성했습니다
### 체크리스트
- [ ] 빌드에 성공했나요?
- [ ] 코드 컨벤션을 잘 지켰나요? (`cmd` + `opt` + `L`)

### 테스트 결과
테스트 결과를 적어주세요!

2024-12-12 15:56 UTC, eunsol-an requested changes
고생해써 유정!
코멘트랑 아래 내용 확인 부탁해!

1. 구독에서 만료, 미구독에서 구독으로 전환될 때 타이머 이미지 on/off 변경 필요할 것 같은데 이 부분 작업은 아직 안된건가?
2. 개발한 뒤에는 아무래도 노션 api 명세보다는 Swagger를 자주 보니까 간단한 설명이 추가되었으면 좋겠습니다용

2024-12-12 15:56 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
> +        String timerUrl = s3Component.generatePresignedUrlsForUpload(shopId, themeId, TYPE_TIMER, 1)
generatePresignedUrlsForUpload 메서드가 list 용으로 만들어둔거라 imageCount 값 1 넣고, 0번째 결과값 가져오는 것 같은데 단일 이미지용 메서드를 추출하는게 낫지 않을까?

2024-12-12 15:56 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
> +        this.useTimerImage = Optional.ofNullable(useTimerImage).orElse(false);
imageUrl DB 저장할 때 구독 여부 판단해서 on/off 값 넣어줘야 할 거 같애!
(구독유저에게는 PC에서 등록한 모든 이미지를 ON상태로 제공, 미구독 유저는 가장 마지막에 등록한 이미지 1개 자동 ON 상태)

2024-12-12 15:56 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
> +        s3Component.deleteObjects(shopId, themeId, TYPE_TIMER, List.of(theme.getTimerImageUrl()));
theme.getTimerImageUrl() null 체크 필요하지 않을까?? 이미지가 없을 땐 삭제 요청이 들어오지 않겠지만 of 메서드에서 NPE 발생할 듯 싶네용

2024-12-14 10:08 UTC, im-gnar commented on src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
> +        List<Long> active;
어짜피 구독 조회때문에 가게의 모든 테마를 다 조회해야하면 불변객체처럼 request 만 검증해서 업데이트하려고 "알림설정상태" 자체를 요청으로 받앗어! 대신 로직이 지금은 for로 조회라 벌크 조회로 변경해야할듯 ㅜㅜ!

2024-12-14 11:39 UTC, im-gnar commented on src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
> +        s3Component.deleteObjects(shopId, themeId, TYPE_TIMER, List.of(theme.getTimerImageUrl()));
오옹 맞네 early return 시켜놧어!!

2024-12-14 11:40 UTC, im-gnar commented on src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
> +        this.useTimerImage = Optional.ofNullable(useTimerImage).orElse(false);
요거 저번에 테스트이미지 등록같은거 얘기하면서 자동 on 안하고 수동으로 켜는거로 하지 않았나??👀

2024-12-14 16:03 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
> +        List<Long> active;
음 구독 상태일 때는 모든 테마를 조회할 필요 없이 해당하는 테마 1개의 on/off 만 설정하면 되는데 그럼 앞단에서 구독 상태 조회를 먼저 하고 구독 상태별로 분기 처리를 하는게 낫지 않을까 싶어..! 어떻게 생각하나용!

2024-12-14 16:03 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
> +        this.useTimerImage = Optional.ofNullable(useTimerImage).orElse(false);
앗 요거는 기획 어떻게 되어 있나 다시 확인 해볼게!

2024-12-14 16:20 UTC, eunsol-an approved these changes
변경된 부분 다 확인했구, 관련해서 몇개 코멘트 남겨뒀어 유정!

구독 관련해서 on/off 되는 쪽은 요구사항 다시 함 확인해봐야 할 것 같아~
이 부분은 제외하고 나머지 수정되면 바로 머지 부탁해!

2024-12-14 16:20 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
> +    public Theme validateThemeAndShop(Long themeId) {
요거 안그래도 중복되는거라 수정해야겠다 생각했는데 바꿔줬네!!ㅋㅋ 고마웡ㅎㅎ

2024-12-14 16:20 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
> +                String timerImage = s3Component.generatePresignedUrlsForUpload(it.getShop().getId(), it.getId(), TYPE_TIMER);
이거 조회 api 맞지? 그럼 ForUpload 말고 ForDownLoad 메서드 사용해야해..!

2024-12-14 16:20 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java
> +    public String generatePresignedUrlsForUpload(Long shopId, Long themeId, String type) {
바로 위 메서드는 복수 리턴이고 이건 단일 리턴이니까 generatePresignedUrlsForUpload 보다는 generatePresignedUrlForUpload 추천해봅니다ㅎㅎ

2024-12-15 06:35 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
> +        List<Long> active;
이 부분은 다음 pr에서 확인하기로 하자!

2024-12-15 06:36 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
> +        this.useTimerImage = Optional.ofNullable(useTimerImage).orElse(false);
기획 쪽에 다시 문의 해봤는데
"구독 유저에게는 PC에서 등록한 모든 이미지를 ON상태로 제공, 미구독 유저는 가장 마지막에 등록한 이미지 1개 자동 ON 상태"
이렇게가 맞다고 하네! 이 부분도 다음 pr 에서 확인하자

2024-12-15 06:36 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
> +                String timerImage = s3Component.generatePresignedUrlsForUpload(it.getShop().getId(), it.getId(), TYPE_TIMER);
다음 pr에 적용 완료

2024-12-15 06:36 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java
> +    public String generatePresignedUrlsForUpload(Long shopId, Long themeId, String type) {
다음 pr에 적용 완료

2024-12-15 06:37 UTC, merged

2024-12-15 07:22 UTC, eunsol-an commented
테마 타이머 배경 이미지 on/off 관련 로직 제외 다음 pr에 적용 완료 https://github.com/Next-Room/NextRoom-be/pull/153