[FEAT] 구독 관련 API 구현
Next-Room/NextRoom-be pull request #73
Opened 2023-10-25 16:20 UTC by eunsol-an

### PR 타입
- [x] 기능 추가

### 반영 브랜치
feature/sub-api → feature/subscription

### 작업 사항
- 기존 ManyToOne이었던 Shop과 Subscription의 관계를 OneToOne으로 변경
- 구독 관련 Enum 정의
  - SubscriptionStatus(구글 기준 구독 상태)
  - UserStatus(프로덕트 기준 유저 상태)
  - SubscriptionPlan(구독 요금제)
- 구독 관련 API 구현
  - 마이페이지에서 필요한 API
  - 유저 상태 API (테마 선택 페이지)
  - 이용권 정보 API (이용권 정보 페이지)
- 안드로이드와의 빠른 테스트를 위해 핵심 로직 먼저 구현하였습니다.
Service단의 예외 처리는 추후 진행하겠습니다.

### 체크리스트
- [x] 빌드에 성공했나요?
- [x] 코드 컨벤션을 잘 지켰나요? (`cmd` + `opt` + `L`)

### 테스트 결과
Postman 테스트 결과 이상 없습니다!

2023-10-26 06:34 UTC, delphox60 requested changes
잠도 줄여가면서 정말 고생 많으셨습니다..
역시 백엔드팀의 대들보입니다 👍

2023-10-26 06:34 UTC, delphox60 commented on src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
> +    @GetMapping("/mypage")
프론트에서 사용하는 axios에서 GET 메서드로 body를 사용하지 못할거에요 !! 몇몇 http 클라이언트는 GET 메서드의 body 사용 지원이 안된다고 하네요

subscriptionId 값만 요청에 담을 거라면 path parameter나 query parameter를 사용하는게 좋을 것 같습니다 👍

2023-10-26 06:34 UTC, delphox60 commented on src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
> +    public ResponseEntity<BaseResponse> getUserStatus(
여기도 마찬가지로 path/query parameter 사용하는게 좋을 것 같습니다!

2023-10-26 06:34 UTC, delphox60 commented on src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
> +        @RequestBody SubscriptionDto.SubscriptionInfoRequest request) {
DTO 클래스는 가독성을 위해 static import로 사용하면 좋을 것 같습니다 👍👍

2023-10-26 06:34 UTC, delphox60 commented on src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
> +    @GetMapping("/mypage")
생각해 보니 shop과 subscription이 1:1 relation이고 JWT 토큰을 사용하니 인자를 꼭 받지 않더라도 SecurityContext에서 유저 정보를 받아오는 방법도 있을 것 같아요!

2023-10-26 06:34 UTC, delphox60 commented on src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
> +    public static class SubscriptionInfoRequest {
각 dto가 delete, edit, create 등 어떤 행위에 대한 요청/응답인지를 알 수 있도록 적어주면 좋을 것 같다고 생각했는데, 지금까지 작업한 다른 dto 클래스들을 보니 get 요청에는 행위를 클래스명에 명시하지 않은 거 같네요.!! 혹시 이거에 대해 의견 달아주시면 좋을 것 같습니다 👍👍

2023-10-26 15:58 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
> +    @GetMapping("/mypage")
GET 요청에 body를 담아 보내다니.. 제 실수입니다🤦‍♀️

SecurityContext에서 유저 정보를 받아오는 방법은 좋은 것 같습니다! 저도 고민하던 부분이었는데 추후 검증 로직을 추가하게 된다면 더 좋을 것 같아요~
일단은 SecurityUtil 쪽에 만들어둔 getRequestedShopId 메서드를 사용하는 방향으로 수정하겠습니다 :)

2023-10-26 15:59 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
> +    public ResponseEntity<BaseResponse> getUserStatus(
토큰에 있는 유저 정보를 사용하는 방향으로 수정하였습니다 :)

2023-10-26 16:00 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
> +        @RequestBody SubscriptionDto.SubscriptionInfoRequest request) {
로직 수정에 따라 Request 관련 Dto는 제거하였습니다!

2023-10-26 16:04 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
> +    public static class SubscriptionInfoRequest {
아무래도 get 요청은 주로 Response Dto를 작성하다 보니 다른 add, edit, delete에 비해 행위 보다는 '형태'의 관점에 집중한 것 같습니다. 
행위에 대한 요청과 응답에 대한 형태.. 조금 더 고민해 볼 필요성이 있겠네요 :) 회의 때 얘기 나눠 보시죠!

2023-10-28 03:09 UTC, delphox60 approved these changes
최곱니다 👍👍

2023-10-28 13:34 UTC, merged