[FEAT] RTDN 및 purchase API 기반 결제 상태 관리 구현
Next-Room/NextRoom-be pull request #88
Opened 2023-11-15 11:45 UTC by delphox60

### PR 타입
- [x] 기능 추가

### 반영 브랜치
feature/subscription → develop

### 작업 사항
- 안드로이드 클라이언트에서 최초 결제 시 purchaseToken을 서버로 전달하고, RTDN을 통해 서버에서 purchaseToken을 대조한 뒤 결제 상태를 업데이트하는 로직을 구현했습니다.

### 체크리스트
- [x] 빌드에 성공했나요?
- [x] 코드 컨벤션을 잘 지켰나요? (`cmd` + `opt` + `L`)

### 테스트 결과
결제 테스트가 필요합니다!

2023-11-15 14:57 UTC, eunsol-an requested changes
너무 너무 고생하셨습니다👍
일단은 코멘트 달아두었어요~
한 번 확인해 보시고, 이후 작업은 제가 진행할게요😎

2023-11-15 14:57 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/controller/PaymentController.java
> +    @PostMapping("rtdn")
rtdn 앞에 '/' 가 빠진 것 같은데 의도 된 부분일까요?

2023-11-15 14:57 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/domain/Subscription.java
> +    @Unique
오 처음 보는 애노테이션...!
JPA에서 unique 설정을 위해 주로 `@Column(unique=true)` 이렇게 설정하곤 했는데 같은 의미로 사용한 게 맞을까요?

2023-11-15 14:57 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
> +    public static class updateSubscription {
class 이름의 시작이 왜 대문자에서 소문자로 바뀌었을까요..!?

2023-11-15 14:57 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
> +    }
이 부분은 테스트를 위한 부분일까요?

2023-11-15 14:57 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
> +        subscriptionRepository.save(subscription);
이때 구독 정보가 생성되는 것이 아니라 기존에 가지고 있던 구독 정보에 update 해야 할 것 같아요~
무료 체험을 하다 결제 후 구독을 하게 되면 status가 FREE → SUBSCRIPTION 으로 변경되는 거죠
다른 구독 정보와 함께 subscribed_at도 update 해주어야 합니다!

2023-11-16 07:33 UTC, delphox60 reviewed
코멘트 보고 수정할 부분 반영했구요, reply 한번씩 확인 부탁드립니다!

2023-11-16 15:35 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
> +    }
생성자에서 다뤄도 선언해 주는 곳에서 잡아야 할 것 같긴 하군요..
일단은 이대로 가고 더 나은 방법을 고민해볼게요!

2023-11-16 15:37 UTC, eunsol-an commented on src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
> +        subscriptionRepository.save(subscription);
네 아주 좋네요!!
그럼 무료 체험 끝나기 전 구독 시작 메서드만 구현하면 되겠군요~

2023-11-16 15:39 UTC, eunsol-an approved these changes
최고에요👍👍👍

2023-11-18 04:20 UTC, merged